create table  if not exists  "goals"
(
    id             int not null generated by default as identity
        constraint pk_goals_id primary key,
    name           varchar(255),
    purpose        text,
    completion     double precision,
    serial_id      varchar(70),
    deadline       date,
    created_at     date,
    updated_at     date
);

create table if not exists "initiative"
(
    id int not null generated by default as identity
        constraint pk_initiative_id primary key,
    name varchar(50),
    serial_id      varchar(70),
    goal_id int,
    completion     double precision,
    weight  float,
    created_at date,
    due_date date,
    updated_at date,
    constraint fk_initiative_id foreign key (goal_id) references "goals" (id)  on delete cascade
);

create table if not exists "task"
(
    id              int not null generated by default as identity
        constraint pk_task_id primary key,
    name          varchar(50),
    serial_id      varchar(70),
    description   text,
    initiative_id int,
    completed        bool,
    weight        float,
    created_at    date,
    due_date      date,
    updated_at    date,
    constraint fk_task_id foreign key (initiative_id) references "initiative" (id)  on delete cascade
);

create table if not exists "money"
(
    id              int not null generated by default as identity
        constraint pk_money_id primary key,
    remark          varchar(50),
    serial_id      varchar(70),
    amount          double precision,
    description   text,
    type          int,
    created_at    date,
    transaction_date      date,
    updated_at    date
);

create table if not exists "news"
(
    id              int not null generated by default as identity
        constraint pk_news_id primary key,
    remark          varchar(50),
    serial_id      varchar(70),
    description   text,
    type          int,
    created_at    date,
    occoured_date      date,
    updated_at    date
);

create table if not exists "job"
(
    id              int not null generated by default as identity
        constraint pk_job_id primary key,
    title         varchar(50),
    serial_id     varchar(70),
    company       varchar(50),
    link     text,
    applied_date  date,
    response      boolean,
    interview      boolean,
    jd            text,
    created_at    date,
    updated_at    date
);