spring:
  datasource:
    username: saurab
    password: saurab123
    url: jdbc:mysql://localhost:3306/life
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    change-log: db.changelog/db.changelog-master.xml
